### ISSUE TITLE
enable to set full content of certificate instead of having it downloaded  

### ISSUE THREAD

**Issue by s-bortolussi** [pivotal-cf/cloudfoundry-certificate-truster#1]
Hello guys,

Nice feature !
Just wondering if it makes sense to also give a way to set directly, using a system property, the content of the certificate to add to the truststore ?
Something similar to https://github.com/Orange-OpenSource/spring-boot-ssl-truststore-gen ?

Sebastien

**Comment by william-tran** [comment]
It would be possible to do this programmatically using `SslCertificateTruster.appendToTruststore`, but you'd need to parse the file or PEM yourself. You could write a new class that would handle the interface between the certificate contents and the SslCertificateTruster, so I welcome a PR for that.

**Comment by scottfrederick** [comment]
@s-bortolussi The Java Buildpack will add certs to the truststore from several different locations, including a [buildpack customization](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#custom-ca-certificates), BOSH trusted certs, and Diego container identity certs (via the [container security provider](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_security_provider.md#security-provider)). 

Is there still a use case for apps to manage the truststore via this library as suggested in this issue?

**Comment by s-bortolussi** [comment]
@scottfrederick You are right. We have replaced the use of the suggested library by the Java Buildpack feature you mentioned. I will close this issue.
