### ISSUE TITLE
Key Stores

### ISSUE THREAD

**Issue by jonathanamartin** [pivotal-cf/cloudfoundry-certificate-truster#10]
This may show a lack in my understanding of the Java trust store is managed.  However, I have a need to employ mutual authentication and was wondering if this would facilitate adding client certificates too?

**Comment by vinayu** [comment]
I too have this requirement.

**Comment by william-tran** [comment]
I'm don't think that use case fits into the scope of this library. This is used to append a certificate to the JVM's existing truststore, by default based on $JAVA_HOME/jre/lib/security/cacerts. Appending to the existing one is important, we don't want to lose trust with the root CA certificates. 

When using a keystore for mutual SSL, this is not set to anything by default. So you're able to create a keystore or set the key material in a variety of ways, which don't depend on any existing state of the JVM.

See http://stackoverflow.com/questions/1666052/java-https-client-certificate-authentication for some info on setting a keystore.

**Comment by jonathanamartin** [comment]
Thanks for the followup.  I agree it doesn't make sense.  I'm looking at an alternate approach with the buildpack:

https://github.com/cloudfoundry/java-buildpack/issues/378
