### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jedjebari** [pivotal-cf/cloudfoundry-certificate-truster#11]
Hi

Can you release the lib with the last commits ?
Thanks

**Comment by scottfrederick** [comment]
@jedjebari What's your use case for using this library? It is intended to serve a specific use case with apps running on Cloud Foundry, and there are better ways now to configure trust of certificates in CF. This library will eventually be deprecated in favor of these other approaches.

**Comment by jedjebari** [comment]
Thanks for your answer. I worked on an existing oauth service broker using this lib.
You're right, I tried the container security provider that does the job. I'll update the project with that
