### ISSUE TITLE
Publish release 1.0.2

### ISSUE THREAD

**Issue by PeterWippermann** [pivotal-cf/cloudfoundry-certificate-truster#13]
In #4 you provided a new feature in a Snapshot version. That has been in January.
Could you do a final release please?

**Comment by scottfrederick** [comment]
@PeterWippermann Can you describe your use case for this library? Are the applications you are using this library in running on Cloud Foundry? What is the nature of the SSL certificates that you want your application to automatically trust - self-signed or from an internal root CA, manually generated or generated by CF? 

This project was never intended to be a general-purpose utility for broad use. It served a specific need in some Pivotal products, but there are better ways to get Java applications running on Cloud Foundry to trust self-signed and internal root CA certificates now. This library will be deprecated and maintenance will stop at some point in the (hopefully near) future. 

Here are some links regarding the configuration of custom certificates in CF for use in Java applications: 
* BOSH configuration of trusted certs: http://bosh.io/docs/trusted-certs.html
* Pivotal CF configuration of trusted certs: https://docs.pivotal.io/pivotalcf/1-12/devguide/deploy-apps/trusted-system-certificates.html
* Java buildpack setup of BOSH-provided and Diego-provided custom certs: https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_security_provider.md
* a discussion on delivering custom certificates with applications: https://github.com/cloudfoundry/java-buildpack/issues/516#issuecomment-342505707
