### ISSUE TITLE
Alternative library

### ISSUE THREAD

**Issue by ghost** [pivotal-cf/cloudfoundry-certificate-truster#14]
I realize this library is essentially deprecated and no longer maintained. I'm curious if the Pivotal folks have a recommended alternative for Spring applications that require connecting to SSL resources where a self-signed cert or non-trusted cert chain is in use. We've used this library as a quick fix for getting around these issues without resorting to completely bypassing Java's SSL behaviors (ie. custom RequestFactory for `RestTemplate` that uses a blind `TrustStrategy`). 

We're now trying to use a similar approach for integration tests such as using WireMock to serve mocked HTTPS payloads. This library only ever used the environment variable `TRUST_CERTS` and it would be convenient to have a general purpose library that allows deeper configuration such as by Spring application properties. 

Any help would be greatly appreciated. My searches so far have come up short outside the obvious StackOverflow workarounds.

**Comment by scottfrederick** [comment]
@tomcooperca Can you elaborate on your use case for Spring apps talking to servers or other apps that are using self-signed certs or non-trusted certs? Are the apps in question running on Cloud Foundry or another platform? 

Trusting untrusted SSL certs is of course a dangerous thing to do. This requirement is common in development environments and lab-quality platforms, but should never be done in production. In production environments, platforms should be configured with the certificates necessary for all components to establish the proper trust. As platforms like Cloud Foundry have evolved, they have provided this type of capability at the platform level. Providing these controls at this platform level, controlled by operators, centralizes the security decisions and configuration.

Providing a library that essentially disables or bypasses a major facet of inter-application communication security, while convenient for development, also makes it easy for developers to deploy insecure applications to production. This library was never meant to be a general-purpose way to disable or bypass security, but was meant to solve some specific pain when deploying apps to a Cloud Foundry environment configured with self-signed SSL certs. 

The fact that platforms like CF have made it easier to centralize SSL certificate management at an operations level, and the risk of a library like `cloudfoundry-certificate-truster` allowing individual developers or development teams to easily disable certificate validation in production, led us to strongly discourage the use of this library. 

I don't know of any other libraries that provide this capability, and I suspect others would be similarly hesitant to provide such a thing.

**Comment by ghost** [comment]
Fair enough. This is commonly provided (with the large amounts of red alerts & warnings) by other HTTPS clients in other languages but is always such a pain in Java. Presumably, it's always been the case of "we know better, so don't workaround our SSL stack". Great in principle, not always easy to apply practically.  

I would just argue that not all organizations have the ability to centralize or federate SSL certificate management across a large number of disparate teams ("silos"). Addressing the root problem is not always in control of the teams who have to integrate with these mismanaged systems. Saying "we can't integrate because of broken SSL" is not always acceptable answer in some orgs. I digress..

As one of my favourite `@ThePracticalDev` covers says: https://www.pinterest.com/pin/370280400595904021/ ;)

Thanks for taking the time to answer my issue.

**Comment by ojhughes** [comment]
@tomcooperca Not sure what your use case but it is certainly possible to configure Apache HTTP Client with a `Trust All` strategy http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ssl/TrustSelfSignedStrategy.html

This can then be used to build a default `RestTemplate` that is used by your app

**Comment by tomcooperca** [comment]
@ojhughes that's our workaround for now. I was looking for something similar to the `TRUST_CERTS` functionality of this repo where I can specify (either in config or as an env var) an endpoint that can import the certificate to a temporary keystore. Seems a better compromise than having to ship around the certs in a keystore manually.
