### ISSUE TITLE
Add logging in case of success

### ISSUE THREAD

**Issue by PeterWippermann** [pivotal-cf/cloudfoundry-certificate-truster#4]
As of today only errors while obtaining the certificates will be logged. It would be great to have log output for a successful download and addition to the truststore as well.

Would it be ok to add this? Or would log output in this early phase of application initialisation break something?

**Comment by william-tran** [comment]
I think this is a good idea, and use of a logging lib would replace the use of `System.err.println`: https://github.com/pivotal-cf/cloudfoundry-certificate-truster/blob/1.0.1.RELEASE/src/main/java/io/pivotal/springcloud/ssl/SslCertificateTruster.java#L84

I didn't directly test the case of using logging this early, so only one way to find out! I'd suggest not pulling in any other dependencies though.

**Comment by PeterWippermann** [comment]
Although I'd generally prefer to route all logging through a logging library like `Slf4J`, I can understand that you don't want to introduce transivitive dependencies. That's ok.

In the context of this project two things are for sure:
1. the `certificate-truster` is a module for cloud apps
2. [a 12-factor-app should log](https://12factor.net/logs) on `stdout`

So I think it's ok if you'd just log all successful progress to `System.out`.

**Comment by 1123** [comment]
Good point about SLF4j. Using a logging facade such as SLF4j is the best way for logging in a library. This way we do not force the user of the library to use a particular logging framework. 

I agree that for the moment logging with System.out should be fine. I will submit a pull request for this. Should this be done on the master branch? Or should we have a 1.0.2-SNAPSHOT branch?

**Comment by PeterWippermann** [comment]
Thanks for your support @1123 ! :-)

The default branch [has been set to 1.0.1.RELEASE](https://github.com/pivotal-cf/cloudfoundry-certificate-truster/branches). To me this appears to be strange.

@william-tran on which branch should development be done?

**Comment by william-tran** [comment]
@PeterWippermann I've got the default branch back on to master. I've created a new brach issue/4-better-logging to kick off this logging improvement, and have added in `slf4j-api`. Feel free to make a PR off that branch and log away!

**Comment by PeterWippermann** [comment]
@1123 would you like to rebase your PR #6 on that branch?

**Comment by 1123** [comment]
yes. Done.

**Comment by william-tran** [comment]
Addressed in PR https://github.com/pivotal-cf/cloudfoundry-certificate-truster/pull/8

**Comment by PeterWippermann** [comment]
So can we have a `1.0.2` release please? :-)

**Comment by william-tran** [comment]
Lets try out 1.0.2-BUILD-SNAPSHOT first... but I don't see a new one built
in
http://repo.spring.io/snapshot/io/pivotal/spring/cloud/cloudfoundry-certificate-truster/1.0.2.BUILD-SNAPSHOT.
Let me re-enable the build so we can test it out.

**Comment by william-tran** [comment]
@PeterWippermann Add our snapshots repo to your build and give 1.0.2.BUILD-SNAPSHOT a try.

**Comment by PeterWippermann** [comment]
Works like a charm! I integrated the library in a Spring Boot app. For the sake of documentation, I'll share the output.

## Download error with version 1.0.1

Logging is done on `stderr`

> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR Error downloading certificate asdfsdfsdfas.test.int:443,java.net.UnknownHostException: asdfsdfsdfas.test.int
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR trusting certificate at asdfsdfsdfas.test.int:443 failed due to java.security.cert.CertificateException: Could not obtain server certificate chain
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR java.security.cert.CertificateException: Could not obtain server certificate chain
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.SslCertificateTruster.getUntrustedCertificateInternal(SslCertificateTruster.java:98)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.SslCertificateTruster.getUntrustedCertificate(SslCertificateTruster.java:66)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.SslCertificateTruster.trustCertificateInternal(SslCertificateTruster.java:121)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.trustCertificatesInternal(CloudFoundryCertificateTruster.java:44)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.trustCertificates(CloudFoundryCertificateTruster.java:32)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.<clinit>(CloudFoundryCertificateTruster.java:77)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:420)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:403)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:394)
> 2017-01-18T19:04:43.48+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:261)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at my.App.main(App.java:27)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:498)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
> 2017-01-18T19:04:43.49+0100 [APP/0]      ERR    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

## Download error with version 1.0.2

Logging output is written to `stdout`. This depends on the config of the logger of course.

> 
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT 18:18:18.435 [SSLCertificateTruster:downloader] ERROR io.pivotal.springcloud.ssl.SslCertificateTruster - Error downloading certificate asdfsdfsdfas.test.in
> t:443
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT java.net.UnknownHostException: asdfsdfsdfas.test.int
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.net.Socket.connect(Socket.java:589)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:427)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.SslCertificateTruster$2.run(SslCertificateTruster.java:101)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 2017-01-18T19:18:18.43+0100 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT 18:18:18.439 [main] ERROR io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster - trusting certificate at asdfsdfsdfas.test.int:443 failed
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT java.security.cert.CertificateException: Could not obtain server certificate chain
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.SslCertificateTruster.getUntrustedCertificateInternal(SslCertificateTruster.java:119)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.SslCertificateTruster.getUntrustedCertificate(SslCertificateTruster.java:87)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.SslCertificateTruster.trustCertificateInternal(SslCertificateTruster.java:142)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.trustCertificatesInternal(CloudFoundryCertificateTruster.java:64)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.trustCertificates(CloudFoundryCertificateTruster.java:52)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster.<clinit>(CloudFoundryCertificateTruster.java:96)
> 2017-01-18T19:18:18.44+0100 [APP/0]      OUT    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

## Successful download with version 1.0.2

> 2017-01-18T19:20:35.22+0100 [APP/0]      OUT 18:20:35.218 [main] INFO io.pivotal.springcloud.ssl.CloudFoundryCertificateTruster - trusting certificate at api.system.mycloud.test.int:443 succeeded

**Comment by PeterWippermann** [comment]
IMO it's ready for release ;-)
