### ISSUE TITLE
Grant a permissive license

### ISSUE THREAD

**Issue by PeterWippermann** [pivotal-cf/cloudfoundry-certificate-truster#5]
As of today this project is not published under any license. This makes usage legally doubtful if not even impossible.

Please consider releasing this project under a permissive license.

**Comment by william-tran** [comment]
This was published to maven central under Apache 2, and that metadata should be in the POM for the latest 1.0.1.RELEASE. The actual LICENSE file isn't part of that release tag in the repo, it's been added in master though. I need to re-arrange some things to get the "badge" to show up in github, but for anyones use they should be fine with 1.0.1.RELEASE today under Apache 2.

**Comment by PeterWippermann** [comment]
Hi @william-tran ,
thanks for the update!
A more prominent reference to the project's license on the homepage would be great. Maybe you could name it in the readme.md file and link to `dist/license.txt`?

**Comment by PeterWippermann** [comment]
Just saw your updates to the project's readme file. Looks great to me, thanks! :-)
